# Generated by Django 5.1.1 on 2024-10-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productinorder_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='price_pre_item',
            new_name='price_per_item',
        ),
    ]
