# Generated by Django 5.1.1 on 2024-11-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcategory_product_discount_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
